Create allens groceries.csv
aaaapartment/apartment-accounting pull request #44
Opened 2022-09-04 03:37 UTC by AllenSteinberg2

If applicable, attach a receipt to this PR and optionally describe the transaction.

![WIN_20220903_09_47_03_Pro](https://user-images.githubusercontent.com/100181991/188296121-ae639a81-aacc-4f63-8896-8a5baa4a3760.jpg)

2022-09-04 19:06 UTC, ayuseiya02 requested changes
im not gonna use the cheese cubes or apples

2022-09-04 19:18 UTC, nd-0r approved these changes

2022-09-04 19:28 UTC, nd-0r requested changes
hmmm

2022-09-04 19:45 UTC, nd-0r approved these changes

2022-09-08 18:46 UTC, ayuseiya02 approved these changes

2022-09-08 18:46 UTC, merged